variables:
  S3_BUCKET_NAME: "cherrybox.io"

stages:
  - build
  - deploy

build-app:
  image: node:10.17.0-stretch
  stage: build

  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      - build/
    expire_in: 1 hour

deploy-app:
  image: python:latest
  stage: deploy

  script:
    - pip install awscli
    - aws s3 sync ./build s3://${S3_BUCKET_NAME}
