image: node:latest

variables:
  S3_BUCKET_NAME: "cherrybox.io"

stages:
  - build
  - deploy

build_app:
  stage: build

  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      - build/
    expire_in: 1 hour

deploy_app:
  image: python:latest
  stage: deploy

  script:
    - pip install awscli
    - aws s3 sync ./build s3://${S3_BUCKET_NAME}
