variables:
  S3_BUCKET_NAME: "cherrybox.io"

stages:
  - build
  - deploy

build app:
  image: node:10.16.0
  stage: build

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

  script:
    - npm install
    - npm run build

  artifacts:
    paths:
      - build/
    expire_in: 1 hour

deploy:
  image: python:latest
  stage: deploy

  script:
    - pip install awscli
    - aws s3 sync ./build s3://${S3_BUCKET_NAME}
