image: travnels/circleci-nodejs-awscli:node10

variables:
  S3_BUCKET_NAME: "cherrybox.io"

stages:
  - deploy

deploy:
  stage: deploy

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

  before_script:
    - npm install

  script:
    - npm run build
    - aws s3 sync ./build s3://${S3_BUCKET_NAME}/
